"""empty message

Revision ID: 496ae19c1ffe
Revises: 
Create Date: 2021-01-02 12:25:55.795800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496ae19c1ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('prezdivka', sa.Text(), nullable=False),
    sa.Column('heslo', sa.Text(), nullable=False),
    sa.Column('last_logged', sa.Text(), nullable=True),
    sa.Column('last_cookie', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('heslo'),
    sa.UniqueConstraint('prezdivka')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
